### ISSUE TITLE
Item container cleanup is too aggressive.

### ISSUE THREAD

**Issue by Omnomios** [Omnomios/DynamicBulwarks#6] opened 2018-06-09 03:31 UTC
Now that empty item containers are deleted, cloths/armor/backpacks are deleted from the ground if you leave the items inventory when they are empty, even if its a loot spawn for the wave. i accidentaly entered a ghillie suits inventory, and backed out so my buddy could grab it, and it despawned. this happens with all cloths/armor/backpacks as well as if zues gives containers for those hoarders out there to gather loot for those rainy days you get swarmed horribly.

**Comment by thatParadox** [comment] 2018-06-09 04:33
I mean, I used a box as the bulwark so people could put shit it... 

So I guess we need to create an array that keeps track of everything that's in each of the containers and only delete them if they're empty or if the loot in them is different to what it spawned with.

**Comment by Omnomios** [comment] 2018-06-09 05:12
Or only add the event to the containers that are used for loot spawning?

**Comment by Omnomios** [comment] 2018-06-10 11:47
Checked the code that cleans up... this shouldn't be happening. It's only placing the event on the loot holder containers. It's only on "_lootHolder"
Needs testing to confirm this isn't just a fluke.

**Comment by Omnomios** [comment] 2018-06-11 09:48
Steps to recreate:
1) Find a look pile with backpack, uniform or vest.
2) Open inventory on that loot pile.
3) Close inventory on the loot pile.
4) The whole pile is deleted.

**Comment by Vehementis** [comment] 2018-06-23 13:13
happened to me too.
the Problem is the "ContainerClosed" event handler.
It does not check for every possible Item inside the _lootHolder so it "thinks" its empty and get deleted.
This happens every time you close a _lootHolder that contains anything not in the list of magazineCargo, weaponCargo, backpackCargo. so I added itemCargo and everyContainer to be checked in my pull request.
everyContainer should contain every uniform, vest and backpack inside the _lootHolder.

**Comment by thatParadox** [comment] 2018-11-05 03:30
Thanks Vehementis that fixed this.

**Closed by thatParadox** 2018-11-05 03:30 UTC
Labels: bug, steam, verified
